### ISSUE TITLE
Command Prefaced with `wsl`

### ISSUE THREAD

**Issue by unkwn1code** [echo-bravo-yahoo/ego-rock#1]
When installed and added to my task note it fails to open at all due to this error:

```
plugin:terminal:115 Error: Command failed: wsl task show report
/bin/sh: line 1: wsl: command not found
```

I'm using EndeavourOS, arch linux based. I presume just removing the `wsl` reference should remedy the issue. Maybe adding some extra settings such as shell would also be useful.

**Comment by echo-bravo-yahoo** [comment]
Hey! Thanks for the bug report - this should be fixed in v2.0.0. Can you upgrade / confirm that you're on 2.0.0, then make sure the path in the settings tab is set to `task` (or the absolute path to the taskwarrior binary, if `task` is not on the path)?

If you wrote any queries in ```task-table``` blocks using the v1 syntax, you will need to change the order from `task $report $filter` to `task $filter $report` (e.g., `task list project:home` => `task project:home list`). The v2 syntax more closely resembles the order the taskwarrior CLI uses, and is hopefully more comfortable to use.

![image](https://github.com/echo-bravo-yahoo/ego-rock/assets/759892/9ab0ced2-0cc9-4af7-b9c4-4782cca218d2)

**Comment by echo-bravo-yahoo** [comment]
Had chance to reproduce - fixed by [this commit](https://github.com/echo-bravo-yahoo/ego-rock/commit/8529afdf0fb524a126b737f8ae5ac202f49c3a29). 

v2.0.1 contains the fix and should be available.

**Comment by unkwn1code** [comment]
Works perfect, thanks a bunch
